### ISSUE TITLE
Message not required

### ISSUE THREAD

**Issue by mikebywater** [Entanet/pubsubevent#1]
Just reading through the documentation and as per laravel docs I would expect 
``` php
event(new UserRegistered($user));
```
Where I would anticipate doing something like
``` php
public function __construct(User $user)
{
    $this->user = $user
}
```
inside the event class. On dispatch $this is publish and when SendWelcomeMailListener() fires $this->event->user would contain the user object.

For this I would imagine
``` php
event(new UserRegistered($user, "user_topic"));
```
Where on dispatch $this is json_encoded and fired into the user_topic within kafka. 

The README doesn't read that way to me. It suggests a message is sent instead of the event object

**Comment by mark-jones-entanet** [comment]
Good idea!
89b04756026216e39f3cbb623d486a8e9a94fea4 added to make these alterations.
